spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech_ledger
    username: admin
    password: rootpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true